In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### the aim of this project is to find a new MO SALAH 
### Looking at Salah's features. salah is/has
* Winger
* Fast
* Vision
* High strength
* High shooting accuracy
* High acceleration, stamina, and agility
* Good with penalties

In [79]:
df = pd.read_csv('player_stats.csv', encoding= "latin-1")
df.head()

,player,country,height,weight,age,club,ball_control,dribbling,marking,slide_tackle,...,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes,value
0,Cristian Castro Devenish,Colombia,192,84,22,Atl. Nacional,55,43,NaN,68,...,32,34,41,33,10,11,6,7,9,$1.400.000
1,Silaldo Taffarel,Brazil,181,80,31,Corinthians,69,70,NaN,56,...,65,62,48,46,12,15,14,8,14,$975.00
2,Thomas DÃ¤hne,Germany,193,84,29,Holstein Kiel,25,12,NaN,13,...,20,15,26,16,64,74,65,68,74,$1.100.000
3,Michael Sollbauer,Austria,187,86,33,SK Rapid Wien,46,48,NaN,66,...,25,13,22,19,10,10,8,14,9,$650.00
4,Diego Segovia,Uruguay,191,80,23,Independiente,14,8,NaN,14,...,9,10,16,5,61,59,62,64,64,$300.00

### A few observations from the dataset
* The dataset has 5682 players with 41 characteristics
* It covers players who are over 40 years old
* It doesn't have a position columns which specifies exactly the player's position
* The dataset covers the Goal Keepers as well
* The max value of the player's attributes is 100

In [80]:
df.shape

(5682, 41)

In [81]:
df.columns

Index(['player', 'country', 'height', 'weight', 'age', 'club', 'ball_control',
       'dribbling', 'marking', 'slide_tackle', 'stand_tackle', 'aggression',
       'reactions', 'att_position', 'interceptions', 'vision', 'composure',
       'crossing', 'short_pass', 'long_pass', 'acceleration', 'stamina',
       'strength', 'balance', 'sprint_speed', 'agility', 'jumping', 'heading',
       'shot_power', 'finishing', 'long_shots', 'curve', 'fk_acc', 'penalties',
       'volleys', 'gk_positioning', 'gk_diving', 'gk_handling', 'gk_kicking',
       'gk_reflexes', 'value'],
      dtype='object')

In [82]:
df.describe()

,height,weight,age,ball_control,dribbling,marking,slide_tackle,stand_tackle,aggression,reactions,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
count,5682.000000,5682.000000,5682.000000,5682.000000,5682.000000,0.0,5682.000000,5682.000000,5682.000000,5682.000000,...,5682.000000,5682.000000,5682.000000,5682.000000,5682.000000,5682.000000,5682.00000,5682.000000,5682.000000,5682.000000
mean,181.670539,75.282295,26.316262,58.912179,56.128476,NaN,46.728441,48.820838,56.324006,61.959345,...,47.164203,48.099789,43.299542,48.174938,42.931890,16.187610,16.43805,16.191834,16.071982,16.570222
std,6.829238,6.998971,4.729967,16.567068,18.772075,NaN,20.519430,20.975966,16.846410,8.893309,...,19.463368,18.086672,17.086473,15.781737,17.912619,17.146572,17.63526,16.993154,16.808674,17.942154
min,156.000000,54.000000,17.000000,8.000000,5.000000,NaN,7.000000,7.000000,11.000000,32.000000,...,5.000000,7.000000,4.000000,8.000000,4.000000,2.000000,2.00000,2.000000,2.000000,3.000000
25%,177.000000,70.000000,23.000000,55.000000,51.000000,NaN,27.000000,30.000000,45.000000,56.000000,...,33.000000,36.000000,32.000000,39.000000,30.000000,8.000000,8.00000,8.000000,8.000000,8.000000
50%,182.000000,75.000000,26.000000,63.000000,62.000000,NaN,54.000000,57.000000,60.000000,62.000000,...,51.000000,50.000000,43.000000,49.000000,44.000000,11.000000,11.00000,11.000000,11.000000,11.000000
75%,186.000000,80.000000,30.000000,69.000000,68.000000,NaN,64.000000,66.000000,69.000000,68.000000,...,62.000000,62.000000,56.000000,60.000000,57.000000,14.000000,14.00000,14.000000,14.000000,14.000000
max,204.000000,102.000000,41.000000,94.000000,95.000000,NaN,87.000000,91.000000,96.000000,93.000000,...,91.000000,93.000000,94.000000,92.000000,90.000000,90.000000,90.00000,87.000000,90.000000,89.000000

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 41 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player          5682 non-null   object
 1   country         5682 non-null   object
 2   height          5682 non-null   int64
 3   weight          5682 non-null   int64
 4   age             5682 non-null   int64
 5   club            5682 non-null   object
 6   ball_control    5682 non-null   int64
 7   dribbling       5682 non-null   int64
 8   marking         0 non-null      float64
 9   slide_tackle    5682 non-null   int64
 10  stand_tackle    5682 non-null   int64
 11  aggression      5682 non-null   int64
 12  reactions       5682 non-null   int64
 13  att_position    5682 non-null   int64
 14  interceptions   5682 non-null   int64
 15  vision          5682 non-null   int64
 16  composure       5682 non-null   int64
 17  crossing        5682 non-null   int64
 18  short_pass      5682 non-null   int64
 19  long_pass       5682 non-null   int64
 20  acceleration    5682 non-null   int64
 21  stamina         5682 non-null   int64
 22  strength        5682 non-null   int64
 23  balance         5682 non-null   int64
 24  sprint_speed    5682 non-null   int64
 25  agility         5682 non-null   int64
 26  jumping         5682 non-null   int64
 27  heading         5682 non-null   int64
 28  shot_power      5682 non-null   int64
 29  finishing       5682 non-null   int64
 30  long_shots      5682 non-null   int64
 31  curve           5682 non-null   int64
 32  fk_acc          5682 non-null   int64
 33  penalties       5682 non-null   int64
 34  volleys         5682 non-null   int64
 35  gk_positioning  5682 non-null   int64
 36  gk_diving       5682 non-null   int64
 37  gk_handling     5682 non-null   int64
 38  gk_kicking      5682 non-null   int64
 39  gk_reflexes     5682 non-null   int64
 40  value           5682 non-null   object
dtypes: float64(1), int64(36), object(4)
memory usage: 1.8+ MB

### By applying Exploratory Data Analysis, we found that 
* The value column is of object data type
* The marking column is all empty
* fk_acc column is referring to Free Kick Accuracy
* No misspellings or mistakes in column names
* Looking at the duplicated values, there are 3 
#### Thus, changes can be made
* Remove the null column
* Change the value column into int64
* The duplicated values are for different players

In [84]:
df.dtypes

player             object
country            object
height              int64
weight              int64
age                 int64
club               object
ball_control        int64
dribbling           int64
marking           float64
slide_tackle        int64
stand_tackle        int64
aggression          int64
reactions           int64
att_position        int64
interceptions       int64
vision              int64
composure           int64
crossing            int64
short_pass          int64
long_pass           int64
acceleration        int64
stamina             int64
strength            int64
balance             int64
sprint_speed        int64
agility             int64
jumping             int64
heading             int64
shot_power          int64
finishing           int64
long_shots          int64
curve               int64
fk_acc              int64
penalties           int64
volleys             int64
gk_positioning      int64
gk_diving           int64
gk_handling         int64
gk_kicking          int64
gk_reflexes         int64
value              object
dtype: object

In [85]:
df.isnull().sum()

player               0
country              0
height               0
weight               0
age                  0
club                 0
ball_control         0
dribbling            0
marking           5682
slide_tackle         0
stand_tackle         0
aggression           0
reactions            0
att_position         0
interceptions        0
vision               0
composure            0
crossing             0
short_pass           0
long_pass            0
acceleration         0
stamina              0
strength             0
balance              0
sprint_speed         0
agility              0
jumping              0
heading              0
shot_power           0
finishing            0
long_shots           0
curve                0
fk_acc               0
penalties            0
volleys              0
gk_positioning       0
gk_diving            0
gk_handling          0
gk_kicking           0
gk_reflexes          0
value                0
dtype: int64

In [86]:
df[df.duplicated() == True]

,player,country,height,weight,age,club,ball_control,dribbling,marking,slide_tackle,...,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes,value
158,Maxime CrÃ©peau,Canada,180,88,29,LAFC,45,19,NaN,17,...,16,14,23,19,70,72,70,70,75,$2.200.000
159,Stefan Thesker,Germany,190,84,32,Holstein Kiel,55,45,NaN,64,...,33,31,42,40,14,13,7,10,12,$700.00
160,Cameron John,England,181,78,24,Rochdale,55,53,NaN,57,...,34,25,32,28,8,13,9,7,8,$350.00

In [87]:
df.drop(['marking'], axis = 1, inplace = True)

In [88]:
df['value'] = df['value'].str.split('$', expand= True)[1]
df['value'] = df['value'].str.replace('.', '').astype("int64")

### Filtering the dataset based on the criteria we have specified
 1. neglecting the Goal Keepers
 2. the Players under 18
 3. the Players over 27

In [92]:
dropped_columns = ['gk_positioning', 'gk_diving', 'gk_handling', 'gk_kicking','gk_reflexes']

df.drop(dropped_columns, axis= 1, inplace= True)

In [111]:
df_filtered = df[df['age'].between(19, 27)]