In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

### the aim of this project is to find a new MO SALAH 
### Looking at Salah's features. salah is/has
* Winger
* Fast
* Vision
* High strength
* High shooting accuracy
* High acceleration, stamina, and agility
* Good with penalties

In [91]:
df = pd.read_csv('player_stats.csv', encoding= "latin-1")
df.head()

,player,country,height,weight,age,club,ball_control,dribbling,marking,slide_tackle,...,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes,value
0,Cristian Castro Devenish,Colombia,192,84,22,Atl. Nacional,55,43,NaN,68,...,32,34,41,33,10,11,6,7,9,$1.400.000
1,Silaldo Taffarel,Brazil,181,80,31,Corinthians,69,70,NaN,56,...,65,62,48,46,12,15,14,8,14,$975.00
2,Thomas DÃ¤hne,Germany,193,84,29,Holstein Kiel,25,12,NaN,13,...,20,15,26,16,64,74,65,68,74,$1.100.000
3,Michael Sollbauer,Austria,187,86,33,SK Rapid Wien,46,48,NaN,66,...,25,13,22,19,10,10,8,14,9,$650.00
4,Diego Segovia,Uruguay,191,80,23,Independiente,14,8,NaN,14,...,9,10,16,5,61,59,62,64,64,$300.00

### A few observations from the dataset
* The dataset has 5682 players with 41 characteristics
* It covers players who are over 40 years old
* It doesn't have a position columns which specifies exactly the player's position
* The dataset covers the Goal Keepers as well
* The max value of the player's attributes is 100

In [92]:
df.shape

(5682, 41)

In [93]:
df.columns

Index(['player', 'country', 'height', 'weight', 'age', 'club', 'ball_control',
       'dribbling', 'marking', 'slide_tackle', 'stand_tackle', 'aggression',
       'reactions', 'att_position', 'interceptions', 'vision', 'composure',
       'crossing', 'short_pass', 'long_pass', 'acceleration', 'stamina',
       'strength', 'balance', 'sprint_speed', 'agility', 'jumping', 'heading',
       'shot_power', 'finishing', 'long_shots', 'curve', 'fk_acc', 'penalties',
       'volleys', 'gk_positioning', 'gk_diving', 'gk_handling', 'gk_kicking',
       'gk_reflexes', 'value'],
      dtype='object')

In [94]:
df.describe()

,height,weight,age,ball_control,dribbling,marking,slide_tackle,stand_tackle,aggression,reactions,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
count,5682.000000,5682.000000,5682.000000,5682.000000,5682.000000,0.0,5682.000000,5682.000000,5682.000000,5682.000000,...,5682.000000,5682.000000,5682.000000,5682.000000,5682.000000,5682.000000,5682.00000,5682.000000,5682.000000,5682.000000
mean,181.670539,75.282295,26.316262,58.912179,56.128476,NaN,46.728441,48.820838,56.324006,61.959345,...,47.164203,48.099789,43.299542,48.174938,42.931890,16.187610,16.43805,16.191834,16.071982,16.570222
std,6.829238,6.998971,4.729967,16.567068,18.772075,NaN,20.519430,20.975966,16.846410,8.893309,...,19.463368,18.086672,17.086473,15.781737,17.912619,17.146572,17.63526,16.993154,16.808674,17.942154
min,156.000000,54.000000,17.000000,8.000000,5.000000,NaN,7.000000,7.000000,11.000000,32.000000,...,5.000000,7.000000,4.000000,8.000000,4.000000,2.000000,2.00000,2.000000,2.000000,3.000000
25%,177.000000,70.000000,23.000000,55.000000,51.000000,NaN,27.000000,30.000000,45.000000,56.000000,...,33.000000,36.000000,32.000000,39.000000,30.000000,8.000000,8.00000,8.000000,8.000000,8.000000
50%,182.000000,75.000000,26.000000,63.000000,62.000000,NaN,54.000000,57.000000,60.000000,62.000000,...,51.000000,50.000000,43.000000,49.000000,44.000000,11.000000,11.00000,11.000000,11.000000,11.000000
75%,186.000000,80.000000,30.000000,69.000000,68.000000,NaN,64.000000,66.000000,69.000000,68.000000,...,62.000000,62.000000,56.000000,60.000000,57.000000,14.000000,14.00000,14.000000,14.000000,14.000000
max,204.000000,102.000000,41.000000,94.000000,95.000000,NaN,87.000000,91.000000,96.000000,93.000000,...,91.000000,93.000000,94.000000,92.000000,90.000000,90.000000,90.00000,87.000000,90.000000,89.000000

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 41 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player          5682 non-null   object
 1   country         5682 non-null   object
 2   height          5682 non-null   int64
 3   weight          5682 non-null   int64
 4   age             5682 non-null   int64
 5   club            5682 non-null   object
 6   ball_control    5682 non-null   int64
 7   dribbling       5682 non-null   int64
 8   marking         0 non-null      float64
 9   slide_tackle    5682 non-null   int64
 10  stand_tackle    5682 non-null   int64
 11  aggression      5682 non-null   int64
 12  reactions       5682 non-null   int64
 13  att_position    5682 non-null   int64
 14  interceptions   5682 non-null   int64
 15  vision          5682 non-null   int64
 16  composure       5682 non-null   int64
 17  crossing        5682 non-null   int64
 18  short_pass      5682 non-null   int64
 19  long_pass       5682 non-null   int64
 20  acceleration    5682 non-null   int64
 21  stamina         5682 non-null   int64
 22  strength        5682 non-null   int64
 23  balance         5682 non-null   int64
 24  sprint_speed    5682 non-null   int64
 25  agility         5682 non-null   int64
 26  jumping         5682 non-null   int64
 27  heading         5682 non-null   int64
 28  shot_power      5682 non-null   int64
 29  finishing       5682 non-null   int64
 30  long_shots      5682 non-null   int64
 31  curve           5682 non-null   int64
 32  fk_acc          5682 non-null   int64
 33  penalties       5682 non-null   int64
 34  volleys         5682 non-null   int64
 35  gk_positioning  5682 non-null   int64
 36  gk_diving       5682 non-null   int64
 37  gk_handling     5682 non-null   int64
 38  gk_kicking      5682 non-null   int64
 39  gk_reflexes     5682 non-null   int64
 40  value           5682 non-null   object
dtypes: float64(1), int64(36), object(4)
memory usage: 1.8+ MB

### By applying Exploratory Data Analysis, we found that 
* The value column is of object data type
* The marking column is all empty
* fk_acc column is referring to Free Kick Accuracy
* No misspellings or mistakes in column names
* Looking at the duplicated values, there are 3 
#### Thus, changes can be made
* Remove the null column
* Change the value column into int64
* Dropped the repeated players due to a name conversion from different languages

In [96]:
df.dtypes

player             object
country            object
height              int64
weight              int64
age                 int64
club               object
ball_control        int64
dribbling           int64
marking           float64
slide_tackle        int64
stand_tackle        int64
aggression          int64
reactions           int64
att_position        int64
interceptions       int64
vision              int64
composure           int64
crossing            int64
short_pass          int64
long_pass           int64
acceleration        int64
stamina             int64
strength            int64
balance             int64
sprint_speed        int64
agility             int64
jumping             int64
heading             int64
shot_power          int64
finishing           int64
long_shots          int64
curve               int64
fk_acc              int64
penalties           int64
volleys             int64
gk_positioning      int64
gk_diving           int64
gk_handling         int64
gk_kicking          int64
gk_reflexes         int64
value              object
dtype: object

In [97]:
df.isnull().sum()

player               0
country              0
height               0
weight               0
age                  0
club                 0
ball_control         0
dribbling            0
marking           5682
slide_tackle         0
stand_tackle         0
aggression           0
reactions            0
att_position         0
interceptions        0
vision               0
composure            0
crossing             0
short_pass           0
long_pass            0
acceleration         0
stamina              0
strength             0
balance              0
sprint_speed         0
agility              0
jumping              0
heading              0
shot_power           0
finishing            0
long_shots           0
curve                0
fk_acc               0
penalties            0
volleys              0
gk_positioning       0
gk_diving            0
gk_handling          0
gk_kicking           0
gk_reflexes          0
value                0
dtype: int64

In [98]:
cols = df.columns.drop(['player','club','marking'])

df[df.duplicated(subset=cols, keep=False)]

,player,country,height,weight,age,club,ball_control,dribbling,marking,slide_tackle,...,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes,value
154,Maxime CrÃ©peau,Canada,180,88,29,LAFC,45,19,NaN,17,...,16,14,23,19,70,72,70,70,75,$2.200.000
156,Stefan Thesker,Germany,190,84,32,Holstein Kiel,55,45,NaN,64,...,33,31,42,40,14,13,7,10,12,$700.00
157,Cameron John,England,181,78,24,Rochdale,55,53,NaN,57,...,34,25,32,28,8,13,9,7,8,$350.00
158,Maxime CrÃ©peau,Canada,180,88,29,LAFC,45,19,NaN,17,...,16,14,23,19,70,72,70,70,75,$2.200.000
159,Stefan Thesker,Germany,190,84,32,Holstein Kiel,55,45,NaN,64,...,33,31,42,40,14,13,7,10,12,$700.00
160,Cameron John,England,181,78,24,Rochdale,55,53,NaN,57,...,34,25,32,28,8,13,9,7,8,$350.00
916,Sadio ManÃ©,Senegal,174,69,31,FC Bayern MÃ¼nchen,86,88,NaN,38,...,77,64,75,75,7,10,10,15,14,$101.000.000
5229,Kylian MbappÃ©,France,182,73,24,Paris SG,91,93,NaN,32,...,80,69,84,83,11,13,5,7,6,$153.500.000
5675,Kylian Mbappé,France,182,73,24,Paris SG,91,93,NaN,32,...,80,69,84,83,11,13,5,7,6,$153.500.000
5678,Sadio Mané,Senegal,174,69,31,FC Bayern München,86,88,NaN,38,...,77,64,75,75,7,10,10,15,14,$101.000.000

In [99]:
df.drop(['marking'], axis = 1, inplace = True)

In [100]:
df['value'] = df['value'].str.split('$', expand= True)[1]
df['value'] = df['value'].str.replace('.', '').astype("int64")

In [101]:
df.drop_duplicates(subset= cols, keep='first', inplace= True)

### Filtering the dataset based on the criteria we have specified
 1. neglecting the Goal Keepers
 2. the Players under 18
 3. the Players over 27

In [102]:
dropped_columns = ['gk_positioning', 'gk_diving', 'gk_handling', 'gk_kicking','gk_reflexes']

df.drop(dropped_columns, axis= 1, inplace= True)

In [103]:
df_filtered = df[df['age'].between(19, 27)]

Looking for a player like mo salah, the player should have a high

1) acceleration
2) sprint_speed
3) agility
4) balance
5) dribbling
6) ball_control
7) finishing
8) att_postion
9) reactions
10) composure

To do that, we need to find the position that the player plays in. I am aiming for attack, mid, defence

In [104]:
categorical_columns = ['player','country', 'club']
encoder = OrdinalEncoder()

encoded = encoder.fit_transform(df_filtered[categorical_columns])

e = pd.DataFrame(encoded, columns= encoder.get_feature_names_out())

In [105]:
encoded, e

(array([[ 581.,   24.,   58.],
        [ 733.,  115.,  319.],
        [ 597.,  107.,   69.],
        ...,
        [ 635.,  116.,  118.],
        [2751.,  103.,  383.],
        [2258.,  111.,   24.]]),
       player  country   club
 0      581.0     24.0   58.0
 1      733.0    115.0  319.0
 2      597.0    107.0   69.0
 3     2603.0     91.0   85.0
 4     2943.0     75.0  333.0
 ...      ...      ...    ...
 3382   756.0     37.0    9.0
 3383  1549.0     92.0  103.0
 3384   635.0    116.0  118.0
 3385  2751.0    103.0  383.0
 3386  2258.0    111.0   24.0

 [3387 rows x 3 columns])

In [106]:
df_filtered.columns

Index(['player', 'country', 'height', 'weight', 'age', 'club', 'ball_control',
       'dribbling', 'slide_tackle', 'stand_tackle', 'aggression', 'reactions',
       'att_position', 'interceptions', 'vision', 'composure', 'crossing',
       'short_pass', 'long_pass', 'acceleration', 'stamina', 'strength',
       'balance', 'sprint_speed', 'agility', 'jumping', 'heading',
       'shot_power', 'finishing', 'long_shots', 'curve', 'fk_acc', 'penalties',
       'volleys', 'value'],
      dtype='object')

In [107]:
# Creating a positional score for every player
df_filtered = df_filtered.copy()

df_filtered['attacking_score'] = (
    df_filtered['finishing'] * 0.25 +
    df_filtered['shot_power'] * 0.15 +
    df_filtered['att_position'] * 0.15 +
    df_filtered['sprint_speed'] * 0.10 +
    df_filtered['acceleration'] * 0.10 +
    df_filtered['dribbling'] * 0.10 +
    df_filtered['ball_control'] * 0.05 +
    df_filtered['volleys'] * 0.05 +
    df_filtered['long_shots'] * 0.05
)

df_filtered['midfield_score'] = (
    df_filtered['short_pass'] * 0.20 +
    df_filtered['long_pass'] * 0.15 +
    df_filtered['vision'] * 0.15 +
    df_filtered['ball_control'] * 0.15 +
    df_filtered['composure'] * 0.10 +
    df_filtered['stamina'] * 0.10 +
    df_filtered['agility'] * 0.05 +
    df_filtered['balance'] * 0.05 +
    df_filtered['crossing'] * 0.05
)

df_filtered['defensive_score'] = (
    df_filtered['stand_tackle'] * 0.25 +
    df_filtered['slide_tackle'] * 0.20 +
    df_filtered['interceptions'] * 0.20 +
    df_filtered['strength'] * 0.10 +
    df_filtered['aggression'] * 0.10 +
    df_filtered['heading'] * 0.05 +
    df_filtered['jumping'] * 0.05 +
    df_filtered['reactions'] * 0.05
)

In [108]:
def get_position(row):
    if row['attacking_score'] > row['midfield_score'] and row['defensive_score']:
        return 'att'
    elif row['midfield_score'] > row['attacking_score'] and row['midfield_score'] > row['defensive_score']:
        return 'mid'
    else:
        return 'def'

In [109]:
df_filtered['position_name']= df_filtered.apply(get_position, axis=1)

In [110]:
# while checking the output of this if condition rule. it turns out it is simple yet effective
df_filtered[['player','position_name']][:10]

                      player position_name
0   Cristian Castro Devenish           def
4              Diego Segovia           mid
6            CÃ©dric Zesiger           def
7                Pedro Gomes           def
9               Sibiry Keita           att
10        Abdullah Al Hamdan           att
12          Vilmer RÃ¶nnberg           def
14          Tyreece Campbell           att
15              John Souttar           def
17            Kim Geon Woong           def

Since attacking is not the only thing a typical player would do we need to add a rule that gives a higher weight for attacking but not totally neglect the other positions so:

let's suppose that we will give 60% for attacking, 25% for middle, 15% for defence and we can test this afterwards

since we have so attributes that have different scales (Ex. weight and height)we may need to use a scaler for the data

In [111]:
df[df['club'] == 'Liverpool']

,player,country,height,weight,age,club,ball_control,dribbling,slide_tackle,stand_tackle,...,jumping,heading,shot_power,finishing,long_shots,curve,fk_acc,penalties,volleys,value
5677,Mohamed Salah,Egypt,175,71,31,Liverpool,86,88,41,43,...,69,59,82,92,84,84,69,86,83,99500000

In [112]:
df_filtered['star_player'] = (df_filtered['attacking_score'] * .6 + 
                              df_filtered['midfield_score'] * .25 +
                              df_filtered['defensive_score'] * .15 )

In [113]:
# the percentage of this player being a star
df_filtered['star_percentile'] = df_filtered['star_player'].rank(pct = True) * 100

In [114]:
# lets have a look on the top 20 players we got from out rule 
# the output shows some of the greatest players who play for world's best clubs
top_players = df_filtered.sort_values('star_player', ascending = False).iloc[:20]
top_players

,player,country,height,weight,age,club,ball_control,dribbling,slide_tackle,stand_tackle,...,fk_acc,penalties,volleys,value,attacking_score,midfield_score,defensive_score,position_name,star_player,star_percentile
5229,Kylian MbappÃ©,France,182,73,24,Paris SG,91,93,32,34,...,69,84,83,153500000,91.75,83.85,48.60,att,83.3025,100.000000
3863,Federico Valverde,Uruguay,182,78,25,Real Madrid,85,81,79,82,...,69,59,70,77500000,82.05,83.70,79.00,mid,82.0050,99.970475
1965,Erling Haaland,Norway,195,94,23,Manchester City,82,78,29,53,...,62,79,88,123000000,89.65,72.70,57.60,att,80.6050,99.940951
3416,Lautaro MartÃ­nez,Argentina,174,72,26,Inter,86,84,44,31,...,54,74,90,79500000,84.65,79.30,56.05,att,79.0225,99.911426
961,Bukayo Saka,England,178,65,21,Arsenal,85,88,67,69,...,69,81,70,47500000,80.95,79.60,66.20,att,78.4000,99.881901
862,NicolÃ¡s De la Cruz,Uruguay,167,65,26,River Plate,78,82,70,75,...,74,69,72,15500000,79.25,80.05,71.80,mid,78.3325,99.852377
3770,Federico Chiesa,Italy,175,70,25,Juventus,82,89,44,48,...,62,62,80,48500000,84.90,79.20,50.15,att,78.2625,99.822852
2129,Phil Foden,England,171,69,23,Manchester City,90,86,47,59,...,68,64,59,63500000,80.90,85.00,55.95,mid,78.1825,99.793327
2327,Franck Yannick KessiÃ©,Ivory Coast,183,88,26,FC Barcelona,84,78,78,84,...,54,88,60,41500000,76.45,80.20,81.45,def,78.1375,99.763803
1319,Renato Sanches,Portugal,176,70,26,Paris SG,81,82,65,74,...,68,68,68,20000000,77.20,81.25,74.45,mid,77.8000,99.734278
5447,Marcus Rashford,England,186,70,25,Manchester Utd,82,85,33,38,...,77,85,73,42000000,84.75,76.95,49.55,att,77.5200,99.704753
3649,JoÃ£o FÃ©lix,Portugal,181,72,23,Chelsea,87,88,35,42,...,67,68,83,43500000,82.10,82.25,49.80,mid,77.2925,99.675229
1032,JuliÃ¡n Ãlvarez,Argentina,170,71,23,Manchester City,84,82,46,53,...,74,73,75,21000000,81.35,79.15,57.80,att,77.2675,99.645704
3605,Mason Mount,England,181,74,24,Chelsea,83,82,42,59,...,84,69,75,42000000,79.75,83.00,57.45,mid,77.2175,99.616180
4052,Leroy SanÃ©,Germany,183,80,27,FC Bayern MÃ¼nchen,85,86,35,32,...,83,71,84,46000000,84.10,79.45,45.60,att,77.1625,99.586655
4338,Martin Ãdegaard,Norway,178,68,24,Arsenal,87,86,51,49,...,85,63,76,62000000,78.70,85.30,56.10,mid,76.9600,99.557130
3846,Dejan Kulusevski,Sweden,186,75,23,Spurs,85,85,58,64,...,61,65,80,30500000,78.85,79.85,62.60,mid,76.6625,99.527606
1506,Gedson Fernandes,Portugal,181,71,24,BeÅiktaÅ,78,82,72,77,...,76,60,64,16000000,76.40,78.10,74.10,mid,76.4800,99.498081
5184,Cody Gakpo,Netherlands,189,76,24,Liverpool,84,86,28,38,...,76,68,75,42000000,83.35,76.95,47.70,att,76.4025,99.468556
1535,Ryan Gravenberch,Netherlands,190,77,21,FC Bayern MÃ¼nchen,85,84,59,69,...,69,58,69,19500000,77.25,79.75,66.70,mid,76.2925,99.439032